#page title
page_title                                : c[OFF]line                                # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1539429868                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : c[OFF]line                                # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : FREE                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Your personal tracker for a healthy relationship with caffeine.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Bartosz Buch                                
your_link                                 : https://www.linkedin.com/in/bartoszbuch/                   
your_city                                 : Stuttgart                                
email_address                             : buchbartosz@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : BarTechB/cs50-finalproject
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Track and monitor caffeine
    description                           : You can add different coffee types for your intake and the app will track your caffeine intake over the day.
    fontawesome_icon_name                 : chart-line
    
  - title                                 : Better sleep
    description                           : It helps you reach your caffeine goal in milligrams before going to bed in order to have a restful sleep.
    fontawesome_icon_name                 : bed

  - title                                 : Different sensitivity levels
    description                           : You can customize the app by choosing three different sensitivity levels (low, medium, strong).
    fontawesome_icon_name                 : dumbbell

  - title                                 : Notification
    description                           : You get a Notification after reaching your caffeine goal on your iPhone or Apple Watch.
    fontawesome_icon_name                 : bell

  - title                                 : High caffeine alert
    description                           : You get an Alert after having over 400mg of caffeine. (According to the FDA)
    fontawesome_icon_name                 : exclamation
  
  - title                                 : Three languages
    description                           : The app supports german, english and polish language.
    fontawesome_icon_name                 : globe-europe
   
  - title                                 : NEW! Apple Health Support
    description                           : Track your caffeine intake in your Apple Health App and see your statistics over time.
    fontawesome_icon_name                 : heart 
    

  - title                                 : Dark theme
    description                           : Dark theme is supported!
    fontawesome_icon_name                 : adjust


  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#C5B6B6"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#000000"

feature_icons_foreground_color            : "#C5B6B6"
feature_icons_background_color            : "#403632"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
